const ROUTES = {
	LOGIN: '/login',
	HOME_PAGE: '/',
	SOMETHING_WENT_WRONG: '/something-went-wrong',
	UN_AUTHORIZED: '/un-authorized',
	NOT_FOUND: '/not-found',
	CONVERSION_STEP1: '/conversion/step1',
	CONVERSION_MEMBER_STEP2: '/conversion-member/step2',
	CONVERSION_MEMBER_STEP3: '/conversion-member/step3',
	CONVERSION_MEMBER_STEP4: '/conversion-member/step4',
	CONVERSION_MEMBER_STEP5: '/conversion-member/step5',
	CONVERSION_MEMBER_STEP6: '/conversion-member/step6',
	CONVERSION_BUSINESS_STEP2: '/conversion-business/step2',
	CONVERSION_BUSINESS_STEP3: '/conversion-business/step3',
	CONVERSION_BUSINESS_STEP4: '/conversion-business/step4',
	CONVERSION_BUSINESS_STEP5: '/conversion-business/step5',
	CONVERSION_BUSINESS_STEP6: '/conversion-business/step6',
	REGISTER_STEP1: '/register/step1',
	REGISTER_MEMBER_STEP2: '/register-member/step2',
	REGISTER_MEMBER_STEP3: '/register-member/step3',
	REGISTER_MEMBER_STEP4: '/register-member/step4',
	REGISTER_MEMBER_STEP5: '/register-member/step5',
	REGISTER_MEMBER_STEP6: '/register-member/step6',
	REGISTER_BUSINESS_STEP2: '/register-business/step2',
	REGISTER_BUSINESS_STEP3: '/register-business/step3',
	REGISTER_BUSINESS_STEP4: '/register-business/step4',
	REGISTER_BUSINESS_STEP5: '/register-business/step5',
	REGISTER_BUSINESS_STEP6: '/register-business/step6',
	// 미성년자 가입 진입점 (PR #195) — minor/Step1.tsx 가 보호자 동의 안내 후 minor 플로우 시작.
	REGISTER_MINOR_STEP1: '/register-minor/step1',
	MYPAGE_MEMBER: '/mypage-member',
	MYPAGE_MEMBER_INFORMATION: '/mypage-member/information',
	MYPAGE_MEMBER_INFORMATION_STEP2: '/mypage-member/information/step2',
	MYPAGE_MEMBER_INFORMATION_STEP3: '/mypage-member/information/step3',
	MYPAGE_MEMBER_AFFILIATION: '/mypage-member/affiliation',
	MYPAGE_MEMBER_AFFILIATION_ADD_STEP1: '/mypage-member/affiliation/add/step1',
	MYPAGE_MEMBER_AFFILIATION_ADD_STEP2: '/mypage-member/affiliation/add/step2',
	MYPAGE_MEMBER_AFFILIATION_WITHDRAW_STEP1:
		'/mypage-member/affiliation/withdraw/step1',
	MYPAGE_MEMBER_AFFILIATION_WITHDRAW_STEP2:
		'/mypage-member/affiliation/withdraw/step2',
	MYPAGE_MEMBER_PASSWORD: '/mypage-member/password',
	MYPAGE_MEMBER_PASSWORD_STEP2: '/mypage-member/password/step2',
	MYPAGE_MEMBER_WITHDRAW: '/mypage-member/withdraw',
	MYPAGE_MEMBER_WITHDRAW_STEP2: '/mypage-member/withdraw/step2',
	MYPAGE_MEMBER_WITHDRAW_COMPLETE: '/mypage-member/withdraw/complete',
	MYPAGE_MEMBER_WITHDRAW_FAIL: '/mypage-member/withdraw/fail',
	MYPAGE_BUSINESS: '/mypage-business',
	MYPAGE_BUSINESS_INFORMATION: '/mypage-business/information',
	MYPAGE_BUSINESS_INFORMATION_STEP2: '/mypage-business/information/step2',
	MYPAGE_BUSINESS_INFORMATION_STEP3: '/mypage-business/information/step3',
	MYPAGE_BUSINESS_AFFILIATION: '/mypage-business/affiliation',
	MYPAGE_BUSINESS_AFFILIATION_ADD_STEP1:
		'/mypage-business/affiliation/add/step1',
	MYPAGE_BUSINESS_AFFILIATION_ADD_STEP2:
		'/mypage-business/affiliation/add/step2',
	MYPAGE_BUSINESS_AFFILIATION_WITHDRAW_STEP1:
		'/mypage-business/affiliation/withdraw/step1',
	MYPAGE_BUSINESS_AFFILIATION_WITHDRAW_STEP2:
		'/mypage-business/affiliation/withdraw/step2',
	// 신 정책: 기업 회원은 비밀번호 수정 메뉴 미노출(MypageSideNav 참조).
	// MYPAGE_BUSINESS_PASSWORD* 라우트는 제거 — 진입 경로 없음.
	MYPAGE_BUSINESS_WITHDRAW: '/mypage-business/withdraw',
	MYPAGE_BUSINESS_WITHDRAW_STEP2: '/mypage-business/withdraw/step2',
	MYPAGE_BUSINESS_WITHDRAW_COMPLETE: '/mypage-business/withdraw/complete',
	MYPAGE_BUSINESS_WITHDRAW_FAIL: '/mypage-business/withdraw/fail',
	FIND_ID: '/find-id',
	FIND_ID_RESULT: '/find-id/result',
	FIND_ID_NOT_FOUND: '/find-id/not-found',
	FIND_PASSWORD: '/find-password',
	FIND_PASSWORD_NEW: '/find-password/new',
	FIND_PASSWORD_RESULT: '/find-password/result',
	USE_TERMS: '/use-terms',
	PRIVACY: '/privacy',
	OACX_TEST: '/auth-test',
} as const;

export default ROUTES;
