import type { MypageMemberType } from 'components/MypageLayout';
import ROUTES from 'constants/routes';

const MYPAGE_ROUTES = {
	member: {
		INFORMATION: ROUTES.MYPAGE_MEMBER_INFORMATION,
		INFORMATION_STEP2: ROUTES.MYPAGE_MEMBER_INFORMATION_STEP2,
		INFORMATION_STEP3: ROUTES.MYPAGE_MEMBER_INFORMATION_STEP3,
		AFFILIATION: ROUTES.MYPAGE_MEMBER_AFFILIATION,
		AFFILIATION_ADD_STEP1: ROUTES.MYPAGE_MEMBER_AFFILIATION_ADD_STEP1,
		AFFILIATION_ADD_STEP2: ROUTES.MYPAGE_MEMBER_AFFILIATION_ADD_STEP2,
		AFFILIATION_WITHDRAW_STEP1: ROUTES.MYPAGE_MEMBER_AFFILIATION_WITHDRAW_STEP1,
		AFFILIATION_WITHDRAW_STEP2: ROUTES.MYPAGE_MEMBER_AFFILIATION_WITHDRAW_STEP2,
		PASSWORD: ROUTES.MYPAGE_MEMBER_PASSWORD,
		PASSWORD_STEP2: ROUTES.MYPAGE_MEMBER_PASSWORD_STEP2,
		WITHDRAW: ROUTES.MYPAGE_MEMBER_WITHDRAW,
		WITHDRAW_STEP2: ROUTES.MYPAGE_MEMBER_WITHDRAW_STEP2,
		WITHDRAW_COMPLETE: ROUTES.MYPAGE_MEMBER_WITHDRAW_COMPLETE,
	},
	business: {
		INFORMATION: ROUTES.MYPAGE_BUSINESS_INFORMATION,
		INFORMATION_STEP2: ROUTES.MYPAGE_BUSINESS_INFORMATION_STEP2,
		INFORMATION_STEP3: ROUTES.MYPAGE_BUSINESS_INFORMATION_STEP3,
		AFFILIATION: ROUTES.MYPAGE_BUSINESS_AFFILIATION,
		AFFILIATION_ADD_STEP1: ROUTES.MYPAGE_BUSINESS_AFFILIATION_ADD_STEP1,
		AFFILIATION_ADD_STEP2: ROUTES.MYPAGE_BUSINESS_AFFILIATION_ADD_STEP2,
		AFFILIATION_WITHDRAW_STEP1: ROUTES.MYPAGE_BUSINESS_AFFILIATION_WITHDRAW_STEP1,
		AFFILIATION_WITHDRAW_STEP2: ROUTES.MYPAGE_BUSINESS_AFFILIATION_WITHDRAW_STEP2,
		PASSWORD: ROUTES.MYPAGE_BUSINESS_PASSWORD,
		PASSWORD_STEP2: ROUTES.MYPAGE_BUSINESS_PASSWORD_STEP2,
		WITHDRAW: ROUTES.MYPAGE_BUSINESS_WITHDRAW,
		WITHDRAW_STEP2: ROUTES.MYPAGE_BUSINESS_WITHDRAW_STEP2,
		WITHDRAW_COMPLETE: ROUTES.MYPAGE_BUSINESS_WITHDRAW_COMPLETE,
	},
} as const;

export function getMypageRoute(
	memberType: MypageMemberType,
	key: keyof typeof MYPAGE_ROUTES['member'],
): string {
	return MYPAGE_ROUTES[memberType][key];
}

export default MYPAGE_ROUTES;
