{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idem-registry
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "onepass.labels" . | nindent 4 }}
    app.kubernetes.io/component: idem-registry
  annotations:
    checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app: idem-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: idem-registry
        {{- include "onepass.labels" . | nindent 8 }}
        app.kubernetes.io/component: idem-registry
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if and .Values.registry.serviceAccount .Values.registry.serviceAccount.create }}
      serviceAccountName: {{ .Values.registry.serviceAccount.name | default "idem-registry" }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: idem-registry
          image: {{ include "onepass.image" .Values.registry.image }}
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: idem-registry-config
            - configMapRef:
                name: idem-common-config
            - secretRef:
                name: {{ .Values.registry.secretRef.name }}
          {{- if .Values.registry.startupProbe }}
          startupProbe:
            {{- toYaml .Values.registry.startupProbe | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.registry.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.registry.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: idem-registry
                topologyKey: kubernetes.io/hostname
{{- end }}
