{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: idem-hub-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "idem.hub.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "idem.hub.selectorLabels" . | nindent 6 }}
{{- end }}
